Mhassanin/backend deploy
NarmathaBala/vsts-extension-retrospectives pull request #5
Opened 2022-01-19 02:30 UTC by mhassaninmsft

- builds and deploys the dotnet project to an Azure App service App.
- Updates some outdated dependencies for the project
- Adds a health check endpoint for the backend service for easier debugging/observability.
- Format some of the logic of Azure login to make the script works seamlessly for developer interactive sessions and CI/CD pipelines
- The project is also .NET 6 ready and can be updated after consulting with @polatengin

2022-01-19 19:28 UTC, polatengin requested changes
I left a few comments, other than those, LGTM! 👍 thanks..

2022-01-19 19:28 UTC, polatengin commented on RetrospectiveExtension.Backend/deploy/env_login.sh
> +    #     --tenant="$tenant_id" >/dev/null
PR #6 suggests using non-interactive login using service principals.

I think it would be better if we use the same approach here.

2022-01-19 19:28 UTC, polatengin commented on RetrospectiveExtension.Backend/deploy/env_setup.sh
> +    zip -r "../../../wesbite.zip" .
is there a typo? `wesbite`

2022-01-19 19:28 UTC, polatengin commented on RetrospectiveExtension.Backend/deploy/env_setup.sh
> +        --name "app-${resource_name_suffix}" --src-path "bin/wesbite.zip"
if `wesbite` is a typo, it needs to be fixed here too

2022-01-20 17:14 UTC, argoldbe commented on RetrospectiveExtension.Backend/deploy/env_login.sh
> +    #     --tenant="$tenant_id" >/dev/null
@polatengin Mohamed and I discussed this and he will be reverting to the original approach.

2022-01-20 20:14 UTC, argoldbe commented on RetrospectiveExtension.Backend/deploy/env_setup.sh
> +    echo "####  Deploying App Settings #######"
nit: fix # count and spacing to match other echo stmts

2022-01-20 20:14 UTC, argoldbe commented on RetrospectiveExtension.Backend/deploy/env_setup.sh
> +    echo "###    Publishing backend project      #####"
nit: fix # count and spacing to match other echo stmts

2022-01-20 20:15 UTC, argoldbe commented on RetrospectiveExtension.Backend/deploy/env_setup.sh
> +         --query defaultHostName --output tsv)
nit: fix last param indent

2022-01-20 21:08 UTC, polatengin approved these changes
thanks, it looks good to me 💯

2022-01-20 21:30 UTC, argoldbe commented on RetrospectiveExtension.Backend/deploy/env_setup.sh
> +    echo "backend service deployed at ${backend_service_url}, to check the health of the deployment visit ${backend_health_check}"
I ran through the full e2e from scratch and it worked great small nit. After seeing the output ("backend service deployed at app-axgold-retro-test1.azurewebsites.net, to check the health of the deployment visit https://app-axgold-retro-test1.azurewebsites.net/health")I would change this slightly to read - "Backend service deployed at app-axgold-retro-test1.azurewebsites.net. To check the health of the deployment visit https://app-axgold-retro-test1.azurewebsites.net/health."

2022-01-20 21:31 UTC, argoldbe approved these changes

2022-01-20 21:34 UTC, merged

2022-01-20 21:35 UTC, argoldbe commented
Not for the PR but I was thinking in a future PR we should add the az cli to the dev container so that a dev can run the setup script from with VS Code / dev container.

2022-01-20 21:36 UTC, mhassaninmsft commented
> 

yeah that is a great idea

2022-01-20 22:10 UTC, polatengin commented
> Not for the PR but I was thinking in a future PR we should add the az cli to the dev container so that a dev can run the setup script from with VS Code / dev container.

that's a good idea, when this PR merged to the microsoft repo, I'll add az cli to the devcontainer, for sure...